name: fuzz

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  fuzz:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab

      - name: Install Rust toolchain
        run: rustup default nightly

      - name: Install cargo-afl
        run: cargo install cargo-afl

      - name: Configure AFL
        run: cargo afl config --build --force && cargo afl system-config

      - name: Canary
        run: fuzz/canary.sh
